version: '3.9'

services:
  dart-api:
    container_name: 'dart-api'
    build:
      context: ./
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - deps:/root/.pub-cache/
    env_file:
      - env.local

volumes:
  deps:

# libtdjson.so || libtdjson.so.1.8.0
