version: '3.9'

services:
  echo-cli:
    tty: true
    container_name: 'echo-cli'
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - env.local
    volumes:
      - tdlib-data:/var/lib/tdlib:rw
      - sqlite-data:/var/lib/sqlite:rw

volumes:
  tdlib-data:
  sqliote-data: