version: '3.9'

services:
  echo-cli-0:
    tty: true
    stdin_open: true
    container_name: 'echo-cli-0'
    hostname: 'echo-cli-0'
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PATH_TD_JSON_LIB=/usr/local/lib/libtdjsonlc.so
      - PATH_TD_JSON_LIB_DATA=/var/lib/tdlib
      - PATH_DB_MESSAGE=/var/lib/sqlite/message.db
      - LOG_LEVEL=info
      - LIBTDJSON_LOGLEVEL=warning
      - RUN_FOREVER=false

      - API_ID_0=0
      - API_HASH_0=0
      - PHONE_0=0
      - PROXY_OPTION_0=
      - CHATS_NAMES_0=[]
    volumes:
      - tdlib-data:/var/lib/tdlib:rw
      - sqlite-data:/var/lib/sqlite:rw

volumes:
  tdlib-data:
  sqlite-data:
