name: telegram_client
version: 0.0.1
environment:
  sdk: '>=2.17.0 <3.0.0'
publish_to: none
dependencies:
  path: ^1.8.3
  uuid: ^3.0.6
  td_json_client: 
    path: ../td_json_client
    version: ^0.0.1
  sqlite3: ^1.9.1
  cron: ^0.5.1
  http: ^0.13.5
dev_dependencies: {lints: ^2.0.0}
