name: td_json_client
version: 0.0.1
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  ffi: ^1.2.1

dev_dependencies:
  ffigen: ^5.0.0
  lints: ^1.0.1
ffigen:
  name: TdJsonClient
  description: Generate binding to tdlib JSON
  output: 'lib/td_json_client.dart'
  headers:
    entry-points:
      - '/app/td/tdlib/include/td/telegram/td_json_client.h'
