name: td_json_client
version: 0.0.1
environment:
  sdk: '>=2.17.0 <3.0.0'
publish_to: none
dependencies:
  ffi: ^2.0.0
  path: ^1.8.0
  logging: ^1.0.2
  quiver: ^3.1.0
dev_dependencies: 
  ffigen: ^6.0.1
  lints: ^2.0.0
  petitparser: ^5.0.0
  mustache_template: ^2.0.0
  recase: ^4.0.0
ffigen:
  name: LibTdJsonLC
  output: 'lib/src/lib_td_json_log_callback.dart'
  headers:
    entry-points:
      - 'lib/src/log_callback/lib_td_json_log_callback.h'
