name: td_json_client
version: 0.0.1
environment:
  sdk: '>=2.17.0 <3.0.0'
publish_to: none
dependencies:
  ffi: ^2.0.0
  path: ^1.8.0
  logging: ^1.0.2
  ffigen: ^6.0.1
dev_dependencies: {lints: ^2.0.0}
ffigen:
  output: 'lib/src/lib_td_json.dart'
  headers:
    entry-points:
      - '${HOME}/td/td/telegram/td_json_client.h'
