apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: aquarius
  name: aquarius
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: aquarius
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aquarius
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: {{ .Values.configEnvs.AQUARIUS_LOG_LEVEL | quote }}
        - name: AQUARIUS_URL
          value: {{ .Values.configEnvs.AQUARIUS_URL | quote }}
        - name: AQUARIUS_WORKERS
          value: {{ .Values.configEnvs.AQUARIUS_WORKERS | quote }}
        - name: DB_HOSTNAME
          value: {{ .Values.configEnvs.AQUARIUS_DB_HOSTNAME | quote }}
        - name: DB_MODULE
          value: {{ .Values.configEnvs.AQUARIUS_DB_MODULE | quote }}
        - name: DB_NAME
          value: {{ .Values.configEnvs.AQUARIUS_DB_NAME | quote }}
        - name: DB_PORT
          value: {{ .Values.configEnvs.AQUARIUS_DB_PORT | quote }}
        - name: DB_SCHEME
          value: {{ .Values.configEnvs.AQUARIUS_DB_SCHEME | quote }}
        - name: DB_USERNAME
          value: {{ .Values.secretEnvs.AQUARIUS_DB_USERNAME | quote }}
        - name: DB_PASSWORD
          value: {{ .Values.secretEnvs.AQUARIUS_DB_PASSWORD | quote }}
        - name: DB_SSL
          value: {{ .Values.configEnvs.AQUARIUS_DB_SSL | quote }}
        - name: RUN_AQUARIUS_SERVER
          value: "1"
        - name: RUN_EVENTS_MONITOR
          value: "0"
        - name: EVENTS_ALLOW
          value: "0"
        - name: CONFIG_FILE
          value: config.ini
        - name: ALLOWED_PUBLISHERS
          value: '[""]'
        image: oceanprotocol/aquarius:v5.1.2
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: aquarius
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 800m
            memory: 1Gi
          requests:
            cpu: 800m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
