apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: provider
  name: provider
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: provider
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
      - env:
        - name: ARTIFACTS_PATH
          value: /ocean-provider/artifacts
        - name: NETWORK_URL
          value: |
            {"{{ .Values.configEnvs.CHAIN_ID_0 }}":"{{ .Values.configEnvs.CHAIN_EVENTS_RPC_0 }}"}
        - name: PROVIDER_PRIVATE_KEY
          value: |
            {"{{ .Values.configEnvs.CHAIN_ID_0 }}":"{{ .Values.secretEnvs.PROVIDER_PRIVATE_KEY_0 }}"}
        - name: LOG_LEVEL
          value: {{ .Values.configEnvs.PROVIDER_LOG_LEVEL | quote }}
        - name: OCEAN_PROVIDER_URL
          value: {{ .Values.configEnvs.PROVIDER_URL | quote }}
        - name: OCEAN_PROVIDER_WORKERS
          value: {{ .Values.configEnvs.PROVIDER_WORKERS | quote }}
        - name: IPFS_GATEWAY
          value: {{ .Values.configEnvs.PROVIDER_IPFS_GATEWAY | quote }}
        - name: OCEAN_PROVIDER_TIMEOUT
          value: "9000"
        - name: OPERATOR_SERVICE_URL
          value: {{ .Values.configEnvs.PROVIDER_OPERATOR_SERVICE_URL | quote }}
        - name: AQUARIUS_URL
          value: {{ .Values.configEnvs.PROVIDER_AQUARIUS_URL | quote }}
        - name: UNIVERSAL_PRIVATE_KEY
          value: {{ .Values.secretEnvs.PROVIDER_UNIVERSAL_PRIVATE_KEY | quote }}
        - name: REQUEST_TIMEOUT
          value: "10"
        image: oceanprotocol/provider-py:latest
        imagePullPolicy: Always
        name: provider
        ports:
        - containerPort: 8030
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 700Mi
          requests:
            cpu: 500m
            memory: 700Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
