{{- if .Values.appSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "ocean.labels" . | nindent 4 }}
type: Opaque
data:
  PUBLISH_IPFS_USERNAME: {{ .Values.secretEnvs.PUBLISH_IPFS_USERNAME | quote }}
  PUBLISH_IPFS_PASSWORD: {{ .Values.secretEnvs.PUBLISH_IPFS_PASSWORD | quote }}
  PUBLISH_FACTORY_DEPLOYER_PRIVATE_KEY: {{ .Values.secretEnvs.PUBLISH_FACTORY_DEPLOYER_PRIVATE_KEY | quote }}
{{- end }}
