[package]
name = "analytics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emojis = "0.6.1"
unicode-segmentation = "1.10.1"
wasm-bindgen = "0.2.89"

[lib]
crate-type = ["cdylib"]
