version: 2.1
jobs:
  build_and_push_docker_image:
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      - IMAGE: echo
      - GOOGLE_PROJECT_ID: jovial-meridian-249123
    steps:
      - checkout
      # - run:
      #     name: Prepare environment
      #     command: |
      #       echo "export GCP_IMAGE=gcr.io/${GOOGLE_PROJECT_ID}/${IMAGE}" >> $BASH_ENV
      #       echo "export TIMESTAMP=$(date +%s)" >> $BASH_ENV
      #       sudo apt-get update
      #       sudo apt-get install -y git tar
      #       echo ${GOOGLE_SERVICE_ACCOUNT} > $HOME/service-account.json
      #       echo "export GOOGLE_APPLICATION_CREDENTIALS=$HOME/service-account.json" >> $BASH_ENV
      #       pip install build
      # - run:
      #     shell: /bin/bash
      #     name: Build package and publish to repo
      #     command: | 
      #       make build

      # - run:
      #    name: Login into gcr
      #    command: |
      #       echo ${GCLOUD_SERVICE_KEY} | docker login -u _json_key --password-stdin https://gcr.io

      # - setup_remote_docker:
      #     version: 20.10.14
      #     docker_layer_caching: true

      # - run:
      #     name: Build docker image
      #     command: | 
      #       docker build -t ${IMAGE}:${CIRCLE_BUILD_NUM} .

      # - run:
      #     name: Tag docker image
      #     command: | 
            
      #       if [[ ${CIRCLE_BRANCH} == "main" ]]; then
      #         docker tag ${IMAGE}:${CIRCLE_BUILD_NUM} ${GCP_IMAGE}:${CIRCLE_SHA1}
      #         docker tag ${IMAGE}:${CIRCLE_BUILD_NUM} ${GCP_IMAGE}:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7}-${TIMESTAMP}
      #       fi

      #       if [[ ! -z ${CIRCLE_TAG} ]]; then
      #         docker tag ${IMAGE}:${CIRCLE_BUILD_NUM} ${GCP_IMAGE}:${CIRCLE_TAG}
      #       fi


      # - run:
      #     name: Push docker image to registry
      #     command: | 

      #       if [[ ${CIRCLE_BRANCH} == "main" ]]; then
      #         docker push ${GCP_IMAGE}:${CIRCLE_SHA1}
      #         docker push ${GCP_IMAGE}:${CIRCLE_BRANCH}-${CIRCLE_SHA1:0:7}-${TIMESTAMP}
      #       fi

      #       if [[ ! -z ${CIRCLE_TAG} ]]; then
      #         docker push ${GCP_IMAGE}:${CIRCLE_TAG}
      #       fi

workflows:

  build-and-push-docker-image:
    jobs:
      - build_and_push_docker_image:
          context:
            - GCR
          filters:
            branches:
               only:
                - main
                - chore/circleci
            tags:
              ignore: /.*/

  release-docker-image-tag:
    jobs:
      - build_and_push_docker_image:
          context:
            - GCR
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/