apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "echo.labels" . | nindent 4 }}
data:  
  PATH_TD_JSON_LIB: {{ .Values.configEnvs.PATH_TD_JSON_LIB | quote }}
  PATH_TD_JSON_LIB_DATA: {{ .Values.configEnvs.PATH_TD_JSON_LIB_DATA | quote }}
  PATH_DB_MESSAGE: {{ .Values.configEnvs.PATH_DB_MESSAGE | quote }}
  LOG_LEVEL: {{ .Values.configEnvs.LOG_LEVEL | quote }}
  LIBTDJSON_LOGLEVEL: {{ .Values.configEnvs.LIBTDJSON_LOGLEVEL | quote }}
  
  IPFS_CRON_SCHEDULE: {{ .Values.configEnvs.IPFS_CRON_SCHEDULE | quote }}
  RUN_FOREVER: {{ .Values.configEnvs.RUN_FOREVER | quote }}
  UNPIN_OLD: {{ .Values.configEnvs.UNPIN_OLD | quote }}
  FULL_EXPORT: {{ .Values.configEnvs.FULL_EXPORT | quote }}
  TABLE_DUMP_PATH: {{ .Values.configEnvs.TABLE_DUMP_PATH | quote }}
  
  CONFIG_PATH: {{ .Values.configEnvs.CONFIG_PATH | quote }}
  INGESTER_CONTRACT_RPC_URL: {{ .Values.configEnvs.INGESTER_CONTRACT_RPC_URL | quote }}
  INGESTER_CONTRACT_ADDRESS: {{ .Values.configEnvs.INGESTER_CONTRACT_ADDRESS | quote }}
  INGESTER_CONTRACT_MAX_GAS: {{ .Values.configEnvs.INGESTER_CONTRACT_MAX_GAS | quote }}

  DRY_RUN_0: {{ .Values.configEnvs.DRY_RUN_0 | quote }}
  DRY_RUN_1: {{ .Values.configEnvs.DRY_RUN_1 | quote }}
  DRY_RUN_2: {{ .Values.configEnvs.DRY_RUN_2 | quote }}
  DRY_RUN_3: {{ .Values.configEnvs.DRY_RUN_3 | quote }}
  DRY_RUN_4: {{ .Values.configEnvs.DRY_RUN_4 | quote }}
  DRY_RUN_5: {{ .Values.configEnvs.DRY_RUN_5 | quote }}
  DRY_RUN_6: {{ .Values.configEnvs.DRY_RUN_6 | quote }}
  DRY_RUN_7: {{ .Values.configEnvs.DRY_RUN_7 | quote }}
  DRY_RUN_8: {{ .Values.configEnvs.DRY_RUN_8 | quote }}
  DRY_RUN_9: {{ .Values.configEnvs.DRY_RUN_9 | quote }}
  DRY_RUN_10: {{ .Values.configEnvs.DRY_RUN_10 | quote }}
  DRY_RUN_11: {{ .Values.configEnvs.DRY_RUN_11 | quote }}
  DRY_RUN_12: {{ .Values.configEnvs.DRY_RUN_12 | quote }}
  DRY_RUN_13: {{ .Values.configEnvs.DRY_RUN_13 | quote }}
  DRY_RUN_14: {{ .Values.configEnvs.DRY_RUN_14 | quote }}
  DRY_RUN_15: {{ .Values.configEnvs.DRY_RUN_15 | quote }}
  DRY_RUN_16: {{ .Values.configEnvs.DRY_RUN_16 | quote }}
  DRY_RUN_17: {{ .Values.configEnvs.DRY_RUN_17 | quote }}
  DRY_RUN_18: {{ .Values.configEnvs.DRY_RUN_18 | quote }}
  DRY_RUN_19: {{ .Values.configEnvs.DRY_RUN_19 | quote }}
  DRY_RUN_20: {{ .Values.configEnvs.DRY_RUN_20 | quote }}
  DRY_RUN_21: {{ .Values.configEnvs.DRY_RUN_21 | quote }}
  DRY_RUN_22: {{ .Values.configEnvs.DRY_RUN_22 | quote }}
  DRY_RUN_23: {{ .Values.configEnvs.DRY_RUN_23 | quote }}
  DRY_RUN_24: {{ .Values.configEnvs.DRY_RUN_24 | quote }}
  DRY_RUN_25: {{ .Values.configEnvs.DRY_RUN_25 | quote }}
  DRY_RUN_26: {{ .Values.configEnvs.DRY_RUN_26 | quote }}
  DRY_RUN_27: {{ .Values.configEnvs.DRY_RUN_27 | quote }}
  DRY_RUN_28: {{ .Values.configEnvs.DRY_RUN_28 | quote }}
  DRY_RUN_29: {{ .Values.configEnvs.DRY_RUN_29 | quote }}
  DRY_RUN_30: {{ .Values.configEnvs.DRY_RUN_30 | quote }}
