apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "ingester-telegram.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.configEnvs.ENVIRONMENT | quote }}