apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "echo.labels" . | nindent 4 }}
data:
  PATH_DB_MESSAGE: {{ .Values.configEnvs.PATH_DB_MESSAGE | quote }}
  PATH_TD_JSON_LIB_DATA: {{ .Values.configEnvs.PATH_TD_JSON_LIB_DATA | quote }}