{{- if .Values.appSecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "echo.labels" . | nindent 4 }}
type: Opaque
data:
  API_ID: {{ .Values.secretEnvs.API_ID | b64enc | quote }}
  API_HASH: {{ .Values.secretEnvs.API_HASH | b64enc | quote }}
{{- end }}
