name: sl_cli
description: telegram client library to make bot or userbot Support Telegram Api and Support Tdlib Telegram Database Library.
version: 0.2.1
homepage: https://github.com/azkadev/telegram_client/tree/main/dart/telegram_client/docs
repository: https://github.com/azkadev/telegram_client/tree/main/dart/telegram_client
issue_tracker: https://github.com/azkadev/telegram_client/issues

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0

dependencies: 
  dotenv: ^4.0.1
  ffi: ^1.1.2
  hexaminate: ^0.1.2
  http: ^0.13.4
  telegram_client: ^0.3.5

executables:
  tg_cli: tg_cli