name: echo_cli
version: 0.0.1
environment:
  sdk: '>=2.17.0 <3.0.0'
publish_to: none
dependencies:
  path: ^1.8.2
  args: ^2.3.1
  telegram_client:
    path: ../telegram_client
    version: ^0.0.1
dev_dependencies:
  lints: ^2.0.0
  petitparser: ^5.0.0
  mustache_template: ^2.0.0
  recase: ^4.0.0
