import 'package:td_json_client/api/base.dart';


/// Represents a local file
class LocalFile extends TdObject {
  String get tdType => 'localFile';

  String? extra;
  int? client_id;

  /// Local path to the locally available file part; may be empty
  string? path;

  /// True, if it is possible to download or generate the file
  Bool? can_be_downloaded;

  /// True, if the file can be deleted
  Bool? can_be_deleted;

  /// True, if the file is currently being downloaded (or a local copy is being generated by some other means)
  Bool? is_downloading_active;

  /// True, if the local copy is fully available
  Bool? is_downloading_completed;

  /// Download will be started from this offset. downloaded_prefix_size is calculated from this offset
  int32? download_offset;

  /// If is_downloading_completed is false, then only some prefix of the file starting from download_offset is ready to be read. downloaded_prefix_size is the size of that prefix in bytes
  int32? downloaded_prefix_size;

  /// Total downloaded file size, in bytes. Can be used only for calculating download progress. The actual file size may be bigger, and some parts of it may contain garbage
  int32? downloaded_size;

  LocalFile({
    this.extra,
    this.client_id,
    this.path,
    this.can_be_downloaded,
    this.can_be_deleted,
    this.is_downloading_active,
    this.is_downloading_completed,
    this.download_offset,
    this.downloaded_prefix_size,
    this.downloaded_size,
  });

  LocalFile.fromMap(Map<String, dynamic> map) {
    extra = map['@extra'];
    client_id = map['@client_id'];
    path = map['path'];
    can_be_downloaded = map['can_be_downloaded'];
    can_be_deleted = map['can_be_deleted'];
    is_downloading_active = map['is_downloading_active'];
    is_downloading_completed = map['is_downloading_completed'];
    download_offset = map['download_offset'];
    downloaded_prefix_size = map['downloaded_prefix_size'];
    downloaded_size = map['downloaded_size'];
  }

  Map<String, dynamic> toMap({skipNulls = true}) {
    Map<String, dynamic> map = {
      '@type': tdType,
      '@extra': extra?.toMap(skipNulls: skipNulls),
      '@client_id': client_id?.toMap(skipNulls: skipNulls),
      'path': path?.toMap(skipNulls: skipNulls),
      'can_be_downloaded': can_be_downloaded?.toMap(skipNulls: skipNulls),
      'can_be_deleted': can_be_deleted?.toMap(skipNulls: skipNulls),
      'is_downloading_active': is_downloading_active?.toMap(skipNulls: skipNulls),
      'is_downloading_completed': is_downloading_completed?.toMap(skipNulls: skipNulls),
      'download_offset': download_offset?.toMap(skipNulls: skipNulls),
      'downloaded_prefix_size': downloaded_prefix_size?.toMap(skipNulls: skipNulls),
      'downloaded_size': downloaded_size?.toMap(skipNulls: skipNulls),
    };
    if (skipNulls) {
      map.removeWhere((key, value) => value == null);
    }
    return map;
  }
}
